lib/hw07_web/router.ex
defmodule Hw07Web.Router do
  use Hw07Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Hw07Web.Plugs.FetchUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Hw07Web do
    pipe_through :browser

    get "/", PageController, :index
    resources "/events", EventController
    resources "/users", UserController
    get "/users/:id/prof_pic_hash", UserController, :prof_pic_hash
    resources "/comments", CommentController
    resources "/invites", InviteController
    resources "/sessions", SessionController,
      only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", Hw07Web do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: Hw07Web.Telemetry
    end
  end
end

lib/hw07/events.ex
defmodule Hw07.Events do
  @moduledoc """
  The Events context.
  """

  import Ecto.Query, warn: false
  alias Hw07.Repo

  alias Hw07.Events.Event

  @doc """
  Returns the list of events.

  ## Examples

      iex> list_events()
      [%Event{}, ...]

  """
  def list_events do
    Repo.all(Event)
    |> Repo.preload(:user)
    |> Repo.preload(:invites)
  end

  @doc """
  Gets a single event.

  Raises `Ecto.NoResultsError` if the Event does not exist.

  ## Examples

      iex> get_event!(123)
      %Event{}

      iex> get_event!(456)
      ** (Ecto.NoResultsError)

  """
  def get_event!(id), do: Repo.get!(Event, id)

  def load_comments(%Event{} = event) do
    Repo.preload(event, [comments: :user])
  end

  def load_invites(%Event{} = event) do
    Repo.preload(event, [:invites])
  end

  @doc """
  Creates a event.

  ## Examples

      iex> create_event(%{field: value})
      {:ok, %Event{}}

      iex> create_event(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_event(attrs \\ %{}) do
    %Event{}
    |> Event.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a event.

  ## Examples

      iex> update_event(event, %{field: new_value})
      {:ok, %Event{}}

      iex> update_event(event, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_event(%Event{} = event, attrs) do
    event
    |> Event.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a event.

  ## Examples

      iex> delete_event(event)
      {:ok, %Event{}}

      iex> delete_event(event)
      {:error, %Ecto.Changeset{}}

  """
  def delete_event(%Event{} = event) do
    Repo.delete(event)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking event changes.

  ## Examples

      iex> change_event(event)
      %Ecto.Changeset{data: %Event{}}

  """
  def change_event(%Event{} = event, attrs \\ %{}) do
    Event.changeset(event, attrs)
  end
end

lib/hw07/events/event.ex
defmodule Hw07.Events.Event do
  use Ecto.Schema
  import Ecto.Changeset

  schema "events" do
    field :description, :string
    field :name, :string
    field :when, :date
    belongs_to :user, Hw07.Users.User
    has_many :comments, Hw07.Comments.Comment
    has_many :invites, Hw07.Invites.Invite

    timestamps()
  end

  @doc false
  def changeset(event, attrs) do
    event
    |> cast(attrs, [:name, :when, :description, :user_id])
    |> validate_required([:name, :when, :description, :user_id])
  end
end

lib/hw07_web/controllers/event_controller.ex
defmodule Hw07Web.EventController do
  use Hw07Web, :controller

  alias Hw07.Events
  alias Hw07.Events.Event

  alias Hw07Web.Plugs
  plug Plugs.RequireUser when action
    not in [:index, :show]
  plug :fetch_post when action
    in [:show, :photo, :edit, :update, :delete]
  plug :require_owner when action
    in [:edit, :update, :delete]

  def fetch_post(conn, _args) do
    id = conn.params["id"]
    event = Events.get_event!(id)
    assign(conn, :event, event)
  end

  def require_owner(conn, _args) do
    user = conn.assigns[:current_user]
    event = conn.assigns[:event]

    if user.id == event.user_id do
      conn
    else
      conn
      |> put_flash(:error, "You don't own that!!!")
      |> redirect(to: Routes.page_path(conn, :index))
      |> halt()
    end
  end

  def index(conn, _params) do
    events = Events.list_events()
    render(conn, "index.html", events: events)
  end

  def new(conn, _params) do
    changeset = Events.change_event(%Event{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"event" => event_params}) do
    event_params = event_params
    |> Map.put("user_id", conn.assigns[:current_user].id)
    case Events.create_event(event_params) do
      {:ok, event} ->
        conn
        |> put_flash(:info, "Event created successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    event = conn.assigns[:event]
    |> Events.load_comments()
    |> Events.load_invites()
    comm = %Hw07.Comments.Comment{
      event_id: event.id,
      user_id: current_user_id(conn),
    }
    inn = %Hw07.Invites.Invite{
      event_id: event.id,
    }
    new_comment = Hw07.Comments.change_comment(comm)
    new_invite = Hw07.Invites.change_invite(inn)
    render(conn, "show.html", event: event, new_comment: new_comment, new_invite: new_invite)
  end

  def edit(conn, %{"id" => id}) do
    event = conn.assigns[:event]
    changeset = Events.change_event(event)
    render(conn, "edit.html", event: event, changeset: changeset)
  end

  def update(conn, %{"id" => id, "event" => event_params}) do
    event = Events.get_event!(id)

    case Events.update_event(event, event_params) do
      {:ok, event} ->
        conn
        |> put_flash(:info, "Event updated successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", event: event, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    event = conn.assigns[:event]
    {:ok, _event} = Events.delete_event(event)

    conn
    |> put_flash(:info, "Event deleted successfully.")
    |> redirect(to: Routes.page_path(conn, :index))
  end
end

lib/hw07_web/views/event_view.ex
defmodule Hw07Web.EventView do
  use Hw07Web, :view
end

lib/hw07_web/templates/event/edit.html.eex
<h1>Edit Event</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.event_path(@conn, :update, @event)) %>

<span><%= link "Back", to: Routes.event_path(@conn, :show, @event) %></span>

lib/hw07_web/templates/event/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="row mb-2">
    <%= label f, :name %>&nbsp;
    <%= text_input f, :name %>
    <%= error_tag f, :name %>
  </div>

  <div class="row mb-2">
    <%= label f, :when %>&nbsp;
    <%= date_select f, :when %>
    <%= error_tag f, :when %>
  </div>


  <div class="row mb-2">
    <%= label f, :description %>&nbsp;
    <%= textarea f, :description %>
    <%= error_tag f, :description %>
  </div>

  <div class="row mb-2">
    <%= submit "Save", class: "btn btn-info" %>
  </div>
<% end %>

lib/hw07_web/templates/event/index.html.eex
<h1>Listing Events</h1>

<table class="table table-striped table-dark table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>When</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for event <- @events do %>
    <tr>
      <td><%= event.name %></td>
      <td><%= event.when %></td>
      <td><%= event.description %></td>

      <td>
        <span><%= link "Show", to: Routes.event_path(@conn, :show, event) %></span>
        <span><%= link "Edit", to: Routes.event_path(@conn, :edit, event) %></span>
        <span><%= link "Delete", to: Routes.event_path(@conn, :delete, event), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Event", to: Routes.event_path(@conn, :new), class: "btn btn-success" %></span>

lib/hw07_web/templates/event/new.html.eex
<h1>New Event</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.event_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.page_path(@conn, :index) %></span>

lib/hw07_web/templates/event/show.html.eex
<div>
    <h1><%= @event.name %></h1>
    <h2 class="mb-2 text-muted"><%= @event.when %></h2>
    <p><%= @event.description %></p>


    <%= if have_current_user?(@conn) do %>

  <h4 class="my-2">Invites</h4>

  <ul class="list-group">
  <%= for inv <- @event.invites do %>
    <li class="list-group-item">
      <p><span class="badge bg-dark text-light">
        Invite for <%= inv.email%></span></p>
      <p>Response: <%=inv.response%></p>
      <%= if current_user_is?(@conn, @event.user_id) do %>
        <p><span><%= link "Revoke Invite", to: Routes.invite_path(@conn, :delete, inv), method: :delete, data: [confirm: "Are you sure?"] %></span></p>
      <% end %>
      <%= if email_user_is?(@conn, inv.email) do %>
        <p><span><%= link "Edit Response", to: Routes.invite_path(@conn, :edit, inv) %></span></p>
      <% end %>
    </li>
  <% end %>
  </ul>


    <%= if current_user_is?(@conn, @event.user_id) do %>
  <div class="border border-primary secondary my-2">
    <h5 class="my-2">Add Invites</h5>
      <%= render(
        Hw07Web.InviteView,
        "form.html",
        changeset: @new_invite,
        action: Routes.invite_path(@conn, :create)
      ) %>
      </div>
    <% end %>

  <h4 class="my-2">Comments</h4>

  <ul class="list-group">
  <%= for comm <- @event.comments do %>
    <li class="list-group-item">
      <p><span class="badge bg-dark text-light">Posted by
        <img id="profile-text"
              src="<%= Routes.user_path(@conn, :prof_pic_hash, comm.user)%>"
              class="card-img-top"
              alt="<%= comm.user.name%>'s Profile Photo"
            /><%= comm.user.name%></span></p>
      <p><%=comm.body%></p>
      <%= if current_user_is?(@conn, @event.user_id) or current_user_is?(@conn, comm.user_id) do %>
        <span><%= link "Delete", to: Routes.comment_path(@conn, :delete, comm), method: :delete, data: [confirm: "Are you sure?"] %></span>
      <% end %>
    </li>
  <% end %>
  </ul>

  <div class="border border-primary rounded my-2">
    <h5>Add Comment</h5>
    <%= if have_current_user?(@conn) do %>
      <%= render(
        Hw07Web.CommentView,
        "form.html",
        changeset: @new_comment,
        action: Routes.comment_path(@conn, :create)
      ) %>
      </div>
    <% end %>
  <%= if current_user_is?(@conn, @event.user_id) do %>
    <span><%= link "Edit", to: Routes.event_path(@conn, :edit, @event) %></span>
    &nbsp;
    <% end %>
    <span><%= link "Back", to: Routes.page_path(@conn, :index) %></span>
  </div>
</div>
<% else %>
<h1 class="alert alert-warning" role="alert">Please Log In or Create an Account First!</h1>
<% end %>