lib/hw07_web/router.ex
defmodule Hw07Web.Router do
  use Hw07Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Hw07Web.Plugs.FetchUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Hw07Web do
    pipe_through :browser

    get "/", PageController, :index
    resources "/events", EventController
    resources "/users", UserController
    get "/users/:id/prof_pic_hash", UserController, :prof_pic_hash
    resources "/comments", CommentController
    resources "/invites", InviteController
    resources "/sessions", SessionController,
      only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", Hw07Web do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: Hw07Web.Telemetry
    end
  end
end

lib/hw07_web/views/layout_view.ex
defmodule Hw07Web.LayoutView do
  use Hw07Web, :view
end

lib/hw07_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Events App!!</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
 <body>
      <div role="main" class="container">
      <div class="row p-3 mb-2">
        <%# <div class="column"> %>
        <%# <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <%# <p><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %>
            <%# <% end %>
        <%# </div> %>
         <div class="col">
          <%= link "Home", to: "/" %>
        </div>
        <div class="col">
          <%= link "Create Account", to: Routes.user_path(@conn, :new)%>
        </div>


          <%= if @conn.assigns[:current_user] do %>
          <div class="col">
            <img id="profile-top"
              src="<%= Routes.user_path(@conn, :prof_pic_hash, @current_user)%>"
              class="card-img-top"
              alt="<%= @current_user.name%>'s Profile Photo"
            />
            User: <%= @current_user.name %> |
            <%= link("Logout", to: Routes.session_path(@conn, :delete),
            method: :delete) %> |
            <%= link "Edit User", to: Routes.user_path(@conn, :edit, @current_user) %>
          </div>
          <% else %>
          <div class="col">
            <%= form_for @conn,
                  Routes.session_path(@conn, :create),
                  [class: "form-inline"],
                  fn f -> %>
              <%= text_input f, :email, class: "form-control" %>
              <%= submit "Login", class: "btn btn-secondary" %>
              </div>
            <% end %>
        <% end %>

      </div>

      <hr>

      <%= if get_flash(@conn, :info) do %>
      <p class="alert alert-info" role="alert">
      <%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
      <p class="alert alert-danger" role="alert">
      <%= get_flash(@conn, :error) %></p>
      <% end %>
      <%# This comes from the index page :eyes:%>
      <%= @inner_content %>
    </div>
  </body>
</html>