lib/hw07_web/router.ex
defmodule Hw07Web.Router do
  use Hw07Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Hw07Web.Plugs.FetchUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Hw07Web do
    pipe_through :browser

    get "/", PageController, :index
    resources "/events", EventController
    resources "/users", UserController
    get "/users/:id/prof_pic_hash", UserController, :prof_pic_hash
    resources "/comments", CommentController
    resources "/invites", InviteController
    resources "/sessions", SessionController,
      only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", Hw07Web do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: Hw07Web.Telemetry
    end
  end
end

lib/hw07_web/templates/page/index.html.eex
<div class="row">
  <div class="column">
    <h1>Events You've Created:
    <%= if have_current_user?(@conn) do %>
    &nbsp;&nbsp;&nbsp;&nbsp;<%= link "New Event", to: Routes.event_path(@conn, :new), class: "btn btn-success" %>
    <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <%= for event <- @events do %>
  <%= if  current_user_is?(@conn, event.user_id) do%>
    <div class="column">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= event.name %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= event.when %></h6>
        <p class="card-text"><%= event.description %></p>
        <span><%= link "View", to: Routes.event_path(@conn, :show, event) %></span>
      </div>
    </div>
    </div>
  <% end %>
  <% end %>
</div>

<div class="row mt-4">
<h1>You're Invited To:</h1>
</div>
<div class="row">
  <%= for event <- @events do %>
  <%= for inv <- event.invites do %>
      <%= if email_user_is?(@conn, inv.email) do %>
    <div class="column">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= event.name %></h5>
        <p><span class="badge bg-dark text-light">Hosted By
        <img id="profile-text"
              src="<%= Routes.user_path(@conn, :prof_pic_hash, event.user)%>"
              class="card-img-top"
              alt="<%= event.user.name%>'s Profile Photo"
            /><%= event.user.name%></span></p>
        <h6 class="card-subtitle mb-2 text-muted"><%= event.when %></h6>
        <p class="card-text"><%= event.description %></p>
        <span><%= link "View", to: Routes.event_path(@conn, :show, event) %></span>
      </div>
    </div>
    </div>
  <% end %>
  <% end %>
  <% end %>
</div>